---
- name: create an Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group_name: 'openenv-9kk9c'
    network_resource_id: '/subscriptions/ede7f891-835c-4128-af5b-0e53848e54e7/resourceGroups/openenv-9kk9c/providers/Microsoft.Network/virtualNetworks/aap-vnet'
    region: 'eastus'
    vnet_cidr: '10.0.0.0/16'
    subnet_cidr: '10.0.0.0/24'
    vnet_name: 'aap-vnet'
    subnet_name: 'default'
    network_sec_group_name: "{{ vm_name }}_nsg"
    vm_name: 'demo-vm'
    vm_size: 'Standard_B2as_v2'
    vm_sku: 'ntg_rhel_8_2'
    public_ip_name: "{{ vm_name }}_public_ip"
    nic_name: "{{ vm_name }}_nic"
    admin_user: 'sysadmin'
    admin_password: 'Passw0rd!'
    allow_ssh: 'Allow'
    allow_https: 'Allow'
    allow_rdp: 'Allow'
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCo4AcnaTev9s3XniFXBymq+UOwTjnIol6U36PHaCiJdPohDeHQKYpg1vIB8IXNnqKemVN9gjTmEHU6Ri5nn9wG55qC/rXvKkT9oqO2FKyPkVPYe2BqyuhBj5ilEIMMYDv1spQ2PfeQWmBoGRIzY+2GCExEkf8acbzzH1mNtu7QzbV00cowf/Q14VGB/hVCg1y2y9hndcRtUT3ajl92gMd/06Ebm381guBiY9DMBj9ghhZQeKC5kr4TUahuqM7zmvLcvBsFSGOYT27IOILiRMF6HD/DthX41t+KDf7EYKlGycjnWFVtvOKm6sCHeoFaFPjP/RNauqYMmdhxKwT4QxE8rNAIAU0L2pdWKqYg5WqfpqQsKZleHYH+gaijUusCW9pMkCxMJwxz5gw1520KxOiUKli2e6oL1psff8+7eDuDQmNtAS4XWnciemoK06zqy7uds1/szZi/EGzi7jLVuBGG3ZZYPrknDg57heCvaF5rgW7aN5OzNE3Hq/DlKErzBwk= sysadmin@t490s.home.local"
    w2k19_dc:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest
      
  tasks: 
  
  - name: "create nsg: {{ network_sec_group_name }}"
    azure.azcollection.azure_rm_securitygroup:
      resource_group: "{{ resource_group_name }}"
      name: "{{ network_sec_group_name }}"
      rules:
      - name: ssh
        protocol: Tcp
        destination_port_range: 22
        access: "{{ allow_ssh }}"
        priority: 1001
        direction: Inbound
      - name: https
        protocol: Tcp
        destination_port_range: 443
        access: "{{ allow_https }}"
        priority: 1002
        direction: Inbound
      - name: rdp
        protocol: Tcp
        destination_port_range: 3389
        access: "{{ allow_rdp }}"
        priority: 1003
        direction: Inbound
      - name: winrm
        protocol: Tcp
        destination_port_range:
          - 5985
          - 5986
        access: "{{ allow_rdp }}"
        priority: 1004
        direction: Inbound

  - name: "create virtual nic: {{ nic_name }}"
    azure.azcollection.azure_rm_networkinterface:
      resource_group: "{{ resource_group_name }}"
      name: "{{ nic_name }}"
      virtual_network: "{{ vnet_name }}"
      subnet: "{{ subnet_name }}"
      security_group: "{{ network_sec_group_name }}"
      public_ip: false      
      ip_configurations:
      - name: ipconfig
        primary: true
        #public_ip_address_name: "{{ vm_name }}_public_ip"
        private_ip_allocation_method: Dynamic
      dns_servers:
      - 8.8.8.8

  - name: "create VM: {{ vm_name }}"
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: "{{ resource_group_name }}"
      name: "{{ vm_name }}"
      managed_disk_type: "Standard_LRS"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ admin_user }}"
      admin_password: "{{ admin_password }}"
      network_interfaces: "{{ nic_name }}"
      state: present
      started: true
      os_type: Windows
      tags:
        "name": "{{ vm_name }}"
        "demo": "true"
        "os": "{{ 'windows_2019' if 'w2k19' in os_image }}{{ 'windows_2022' if 'w2k22' in os_image }}"
        "os_type": "windows"
        "os_family": "windows"
        "username": "{{ admin_user }}"
      image: "{{ lookup('ansible.builtin.vars', os_image) }}"
      security_profile:
        security_type: Standard
  
  - name: Create VM script extension to enable HTTPS WinRM listener
    azure_rm_virtualmachineextension:
      name: winrm-extension
      resource_group: "{{ resource_group_name }}"
      virtual_machine_name: "{{ vm_name }}"
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: '1.9'
      settings: '{"fileUris": ["https://raw.githubusercontent.com/tmrblt/ansible-demos/main/files/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
      auto_upgrade_minor_version: true
