---
- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group_name: 'openenv-9kk9c'
    network_resource_id: '/subscriptions/ede7f891-835c-4128-af5b-0e53848e54e7/resourceGroups/openenv-9kk9c/providers/Microsoft.Network/virtualNetworks/aap-vnet'
    network_sec_group_name: "{{ vm_name }}_nsg"
    subnet_name: 'default'
    vm_name: 'demo-vm'
    nic_name: "{{ vm_name }}_nic"
    vnet_name: 'aap-vnet'
    allow_ssh: 'Allow'
    allow_https: 'Allow'
    allow_rdp: 'Allow'
    tasks:
    - name: Create Network Security Group that allows SSH and RDP
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ network_sec_group_name }}"
        rules:
          - name: ssh
            protocol: Tcp
            destination_port_range: 22
            access: "{{ allow_ssh }}"
            priority: 1001
            direction: Inbound
          - name: https
            protocol: Tcp
            destination_port_range: 443
            access: "{{ allow_https }}"
            priority: 1002
            direction: Inbound
          - name: rdp
            protocol: Tcp
            destination_port_range: 3389
            access: "{{ allow_rdp }}"
            priority: 1003
            direction: Inbound
        state: absent

    - name: Create virtual network interface card
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        security_group: "{{ network_sec_group_name }}"
        state: absent

    - name: Create VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        state: absent
