---
- name: delete an Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    resource_group_name: 'openenv-9kk9c'
    network_resource_id: '/subscriptions/ede7f891-835c-4128-af5b-0e53848e54e7/resourceGroups/openenv-9kk9c/providers/Microsoft.Network/virtualNetworks/aap-vnet'
    network_sec_group_name: "{{ vm_name }}_nsg"
    subnet_name: 'default'
    vm_name: 'demo-vm'
    nic_name: "{{ vm_name }}_nic"
    vnet_name: 'aap-vnet'
    allow_ssh: 'Allow'
    allow_https: 'Allow'
    allow_rdp: 'Allow'
    
  tasks:
  
    - name: delete VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        state: absent

    - name: delete virtual nic
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        security_group: "{{ network_sec_group_name }}"
        state: absent
        
    - name: delete nsg
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ network_sec_group_name }}"
        state: absent
