---
- name: create an Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group_name: 'openenv-9kk9c'
    network_resource_id: '/subscriptions/ede7f891-835c-4128-af5b-0e53848e54e7/resourceGroups/openenv-9kk9c/providers/Microsoft.Network/virtualNetworks/aap-vnet'
    region: 'eastus'
    vnet_name: 'aap-vnet'
    subnet_name: 'default'
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCo4AcnaTev9s3XniFXBymq+UOwTjnIol6U36PHaCiJdPohDeHQKYpg1vIB8IXNnqKemVN9gjTmEHU6Ri5nn9wG55qC/rXvKkT9oqO2FKyPkVPYe2BqyuhBj5ilEIMMYDv1spQ2PfeQWmBoGRIzY+2GCExEkf8acbzzH1mNtu7QzbV00cowf/Q14VGB/hVCg1y2y9hndcRtUT3ajl92gMd/06Ebm381guBiY9DMBj9ghhZQeKC5kr4TUahuqM7zmvLcvBsFSGOYT27IOILiRMF6HD/DthX41t+KDf7EYKlGycjnWFVtvOKm6sCHeoFaFPjP/RNauqYMmdhxKwT4QxE8rNAIAU0L2pdWKqYg5WqfpqQsKZleHYH+gaijUusCW9pMkCxMJwxz5gw1520KxOiUKli2e6oL1psff8+7eDuDQmNtAS4XWnciemoK06zqy7uds1/szZi/EGzi7jLVuBGG3ZZYPrknDg57heCvaF5rgW7aN5OzNE3Hq/DlKErzBwk= sysadmin@t490s.home.local"
    public_ip: false
    
    network_sec_group_name: "{{ vm_name }}_nsg"
    vm_name: 'demo-vm'
    vm_size: 'Standard_B2ats_v2'
    public_ip_name: "{{ vm_name }}_public_ip"
    nic_name: "{{ vm_name }}_nic"
    admin_user: 'sysadmin'
    admin_password: 'Passw0rd!'
    inventory: "azure-inventory"
    inventory_source: "azure-source"
    organization: "Default"
    ubuntu_20_04:      
      offer: 0001-com-ubuntu-server-focal
      publisher: canonical
      sku: 20_04-lts-gen2
      version: latest
    centos_7_5:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest
    centos_8_5:
      offer: CentOS
      publisher: OpenLogic
      sku: 8_5-gen2
      version: latest
    debian_11: 
      offer: debian-11
      publisher: Debian
      sku: 11-backports-gen2
      version: latest
    opensuse_15_4:
      offer: openSUSE-leap-15-4
      publisher: SUSE
      sku: gen2
      version: latest
      
  tasks: 
  
  - name: "create nsg: {{ network_sec_group_name }}"
    azure.azcollection.azure_rm_securitygroup:
      resource_group: "{{ resource_group_name }}"
      name: "{{ network_sec_group_name }}"
      rules:
      - name: ssh
        protocol: Tcp
        destination_port_range:
        - 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: https
        protocol: Tcp
        destination_port_range:
        - 443
        - 80
        access: Allow
        priority: 1002
        direction: Inbound
      - name: rdp
        protocol: Tcp
        destination_port_range:
        - 3389
        access: Allow
        priority: 1003
        direction: Inbound
 
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group_name }}"
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
    when: public_ip
    
  - name: "create virtual nic: {{ nic_name }}"
    azure.azcollection.azure_rm_networkinterface:
      resource_group: "{{ resource_group_name }}"
      name: "{{ nic_name }}"
      virtual_network: "{{ vnet_name }}"
      subnet: "{{ subnet_name }}"
      security_group: "{{ network_sec_group_name }}"
      public_ip: "{{ public_ip }}"
      ip_configurations:
      - name: ipconfig
        primary: false
        private_ip_allocation_method: Dynamic
      dns_servers:
      - 8.8.8.8      
  
  - name: "create VM: {{ vm_name }}"
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: "{{ resource_group_name }}"
      name: "{{ vm_name }}"
      managed_disk_type: "Standard_LRS"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ admin_user }}"
      admin_password: "{{ admin_password }}"
      network_interfaces: "{{ nic_name }}"
      state: present
      started: true
      ssh_password_enabled: true
      ssh_public_keys:
      - path: "/home/{{ admin_user }}/.ssh/authorized_keys"
        key_data: "{{ ssh_key }}"
      os_type: Linux
      tags:
        "name": "{{ vm_name }}"
        "aap-demo": "true"
        "os": "{{ 'rhel' if 'rhel' in os_image }}{{ 'centOS' if 'centOS' in os_image }}{{ 'ubuntu' if 'ubuntu' in os_image }}{{ 'Debian' if 'Debian' in os_image }}{{ 'suse' if 'SUSE' in os_image }}"
        "os_type": "linux"
        "os_family": "{{ 'rhel-family' if ('centOS' or 'rhel' or 'RHEL' or 'suse' or 'SUSE') in os_image }}{{ 'debian-family' if ('ubuntu' or 'Debian') in os_image }}"
        "username": "{{ admin_user }}"
      image: "{{ lookup('ansible.builtin.vars', os_image) }}"
      security_profile:
        security_type: Standard
        
  - name: Update a single inventory source
    ansible.controller.inventory_source_update:
      name: "{{inventory_source}}"
      inventory: "{{inventory}}"
      organization: "{{organization}}"  
