---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group_name: 'openenv-9kk9c'
    network_resource_id: '/subscriptions/ede7f891-835c-4128-af5b-0e53848e54e7/resourceGroups/openenv-9kk9c/providers/Microsoft.Network/virtualNetworks/aap-vnet'
    region: 'eastus'
    vnet_cidr: '10.0.0.0/16'
    subnet_cidr: '10.0.0.0/24'
    vnet_name: 'aap-vnet'
    subnet_name: 'default'
    network_sec_group_name: "{{ vm_name }}_nsg"
    vm_name: 'demo-vm'
    vm_size: 'Standard_B2as_v2'
    vm_sku: 'ntg_rhel_8_2'
    public_ip_name: "{{ vm_name }}_public_ip"
    nic_name: "{{ vm_name }}_nic"
    admin_user: 'sysadmin'
    admin_password: 'Passw0rd!'
    allow_ssh: 'Allow'
    allow_https: 'Allow'
    allow_rdp: 'Allow'
    w2k19_dc:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest
        
  tasks:
