---
- name: create an Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group_name: 'openenv-9kk9c'
    network_resource_id: '/subscriptions/ede7f891-835c-4128-af5b-0e53848e54e7/resourceGroups/openenv-9kk9c/providers/Microsoft.Network/virtualNetworks/aap-vnet'
    region: 'eastus'
    vnet_name: 'aap-vnet'
    subnet_name: 'default'
    public_ip: false
    powershell_file_url: 'https://raw.githubusercontent.com/tmrblt/ansible-demos/main/files/ConfigureRemotingForAnsible.ps1' 
    
    network_sec_group_name: "{{ vm_name }}_nsg"
    vm_name: 'demo-vm'
    vm_size: 'Standard_B2as_v2'
    public_ip_name: "{{ vm_name }}_public_ip"
    nic_name: "{{ vm_name }}_nic"
    admin_user: 'sysadmin'
    admin_password: 'Passw0rd!'
    inventory: "azure-inventory"
    inventory_source: "azure-source"
    organization: "Default"
    w2k16_dc:        
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2022-Datacenter
      version: latest
    w2k19_dc:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2019-Datacenter
      version: latest
    w2k22_dc:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2022-Datacenter
      version: latest
      
  tasks: 
  
  - name: "create nsg: {{ network_sec_group_name }}"
    azure.azcollection.azure_rm_securitygroup:
      resource_group: "{{ resource_group_name }}"
      name: "{{ network_sec_group_name }}"
      rules:
      - name: https
        protocol: Tcp
        destination_port_range:
        - 443
        - 80
        access: 'Allow'
        priority: 1001
        direction: Inbound
      - name: rdp
        protocol: Tcp
        destination_port_range: 3389
        access: 'Allow'
        priority: 1002
        direction: Inbound
      - name: winrm
        protocol: Tcp
        destination_port_range:
        - 5985
        - 5986
        access: 'Allow'
        priority: 1003
        direction: Inbound

  - name: "create virtual nic: {{ nic_name }}"
    azure.azcollection.azure_rm_networkinterface:
      resource_group: "{{ resource_group_name }}"
      name: "{{ nic_name }}"
      virtual_network: "{{ vnet_name }}"
      subnet: "{{ subnet_name }}"
      security_group: "{{ network_sec_group_name }}"
      public_ip: "{{public_ip}}"     
      ip_configurations:
      - name: ipconfig
        primary: true
        private_ip_allocation_method: Dynamic
      dns_servers:
      - 8.8.8.8

  - name: "create VM: {{ vm_name }}"
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: "{{ resource_group_name }}"
      name: "{{ vm_name }}"
      managed_disk_type: "Standard_LRS"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ admin_user }}"
      admin_password: "{{ admin_password }}"
      network_interfaces: "{{ nic_name }}"
      state: present
      started: true
      os_type: Windows
      tags:
        "name": "{{ vm_name }}"
        "demo": "true"
        "os": "{{ 'windows_2019' if 'w2k19' in os_image }}{{ 'windows_2022' if 'w2k22' in os_image }}"
        "os_type": "windows"
        "os_family": "windows"
        "username": "{{ admin_user }}"
      image: "{{ lookup('ansible.builtin.vars', os_image) }}"
      security_profile:
        security_type: Standard
  
  - name: Create VM script extension to enable HTTPS WinRM listener
    azure.azcollection.azure_rm_virtualmachineextension:
      name: winrm-extension
      resource_group: "{{ resource_group_name }}"
      virtual_machine_name: "{{ vm_name }}"
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: '1.9'
      settings: '{"fileUris": ["http://10.200.18.35:8080/ansible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ansible.ps1"}'
      auto_upgrade_minor_version: true
        
  - name: Update a single inventory source
    ansible.controller.inventory_source_update:
      name: "{{inventory_source}}"
      inventory: "{{inventory}}"
      organization: "{{organization}}"  
