---
- name: gather windows vm facts
  hosts: windows_servers
  tasks:
  - name: print facts
    debug:
      var: ansible_facts
  - name: print hostvars
    debug:
      var: hostvars[inventory_hostname]
