---
- name: delete a VM on GCP
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    gcp_project: 'openenv-czkgd'
    gcp_zone: 'us-east1-b'
    gcp_region: 'us-east1'
    vm_name: 'demo-vm'
    network_selflink: 'projects/openenv-czkgd/global/networks/demo-vpc'
    subnet_selflink: 'projects/openenv-czkgd/regions/us-east1/subnetworks/demo-subnet'
  
  tasks:
  
  - name: "delete the VM instance: {{ vm_name }}"
    google.cloud.gcp_compute_instance:
      name: "{{ vm_name }}"
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: serviceaccount
      state: absent

  - name: delete a disk
    google.cloud.gcp_compute_disk:
      name: "disk{{ vm_name }}"
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: serviceaccount
      state: absent
    register: disk
