---
- name: create VMs on GCP
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    gcp_project: 'openenv-czkgd'
    gcp_zone: 'us-east1-b'
    gcp_region: 'us-east1'
    vm_name: 'demo-vm'
    network_name: 'demo-vpc'
    subnet_name: 'demo-subnet'
  
  tasks:
  
  - name: create a disk
    google.cloud.gcp_compute_disk:
      name: "disk{{ vm_name }}"
      size_gb: 50  
      source_image: "projects/ubuntu-os-pro-cloud/global/images/ubuntu-pro-2204-jammy-v20231102" #projects/rhel-cloud/global/images/rhel-8-v20231010"
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: serviceaccount
      state: present
    register: disk

  - name: create a google VPC network
    google.cloud.gcp_compute_network:
      name: "{{ network_name }}"
      auto_create_subnetworks: False
      project: "{{ gcp_project }}"
      auth_kind: serviceaccount
      state: present
    register: network
      
  - name: create a subnetwork
    google.cloud.gcp_compute_subnetwork:
      name: "{{ subnet_name }}"
      region: us-east1
      network: "{{ network }}"
      ip_cidr_range: 10.0.0.0/24
      project: "{{ gcp_project }}"
      auth_kind: serviceaccount
      state: present
    register: subnet

  - name: create firewall rules to allow SSH,RDP,HTTPS,ICMP
    google.cloud.gcp_compute_firewall:
      name: vpc-firewall-rules
      allowed:
      - ip_protocol: icmp
      - ip_protocol: tcp
          ports:
          - '22'
          - '80'
          - '443'
          - '3389'
      project: "{{ gcp_project }}"
      network: "{{ network }}"
      auth_kind: serviceaccount
      state: present
    register: firewall_rules

  - name: "create the VM instance: {{ vm_name }}"
    google.cloud.gcp_compute_instance:
      name: "{{ vm_name }}"
      machine_type: e2-standard-4
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk }}"
      - auto_delete: 'true'
        interface: NVME
        type: SCRATCH
        initialize_params:
        disk_type: pd-standard
      labels:
      - env: aap-demo
      network_interfaces:
      - network: "{{ network }}"
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: serviceaccount
      state: present
