- name: linux patch report
  hosts: all
  gather_facts: true
  vars:
    updatelist: []
  tasks:
    - name: list updates
      yum:
        list: updates
        use_backend: yum3
      register: update_result
      when: ansible_os_family == "RedHat"
      
    - name: list updates
      ansible.builtin.apt:
        name: "*"
        state: latest
      check_mode: true
      register: update_result
      when: ansible_os_family == "Debian"
    
    - debug: var=update_result
      when: ansible_os_family == "Debian"
    
    - debug: var=ansible_facts
      when: ansible_os_family == "Debian"

    - name: create array for updates
      set_fact:
        updatelist: "{{ update_result.results | map(attribute='envra') | list }}"
      register: updatelist_result
      when: ansible_os_family == "RedHat"

    - name: create HTMl report
      template:
        src: templates/linux_patch_reports.j2
        dest: /var/www/html/linux_patch_report.html
      delegate_to: "{{ report_server }}"
      run_once: true
