- name: Report updates for Windows WMs
  hosts: all
  gather_facts: true
  vars:
    updatelist: []
  tasks:
    - name: Check for updates 
      become: yes
      become_method: runas
      become_user: Administrator
      win_updates:
        category_names:
        #  - SecurityUpdates
        - CriticalUpdates
        #  - UpdateRollups
        state: searched
        log_path: C:\ansible_wu.txt
      register: update_result
 
    - name: print update titles
      debug: msg=""{{ update_result }}""

    - name: edit list for updates
      set_fact:
        updatelist: "{{ update_result }}"

#    - name: print updates
#      debug:
#        msg: KB is "{{item.value.kb[0]}}" Title is "{{item.value.title}}"
#      loop: "{{lookup('dict',update_result.filtered_updates)}}"

#    - name: create array for updates
#      set_fact:
#        updatelist: "{{updatelist + [item.value.title]}}"
#      loop: "{{lookup('dict',update_result.updates)}}"
#      register: updatelist_result

#    - name: update array for filtered_updates
#     set_fact:
#        updatelist: "{{updatelist + [item.value.title]}}"
#      loop: "{{lookup('dict',update_result.filtered_updates)}}"
#      register: updatelist_result
    
#    - debug: var=updatelist_result

#    - debug: var=updatelist
    
#    - debug: var=ansible_facts 
    
    - name: Create HTMl report
      become: yes
      become_method: sudo
      become_user: root
      template:
        src: patch_report_windows.j2
        dest: /var/www/html/patch_report_windows.html
      delegate_to: "{{ report_server }}"
      run_once: true
