- name: linux patch report
  hosts: all
  gather_facts: no
  vars:
    updatelist: []
  tasks:

    - setup:
      when: ansible_os_family == "RedHat"
      
    - name: list updates
      yum:
        list: updates
        use_backend: yum3
      register: update_result
      when: ansible_os_family == "RedHat"
          
    - debug: var=update_result
      when: ansible_os_family == "RedHat"

    - name: create array for updates
      set_fact:
        updatelist: "{{ update_result.results | map(attribute='envra') | list }}"
      register: updatelist_result
      when: ansible_os_family == "RedHat"

    - name: create HTML report
      template:
        src: templates/patch_report_rhel.j2
        dest: /var/www/html/patch_report_rhel.html
      delegate_to: "{{ report_server }}"
      run_once: true
