- name: linux patch report
  hosts: all
  gather_facts: true
  vars:
    updatelist: []
  tasks:
    - name: list updates
      ansible.builtin.apt:
        name: "*"
        state: latest
      check_mode: true
      register: update_result
      when: ansible_os_family == "Debian"
          
    - debug: var=update_result
      when: ansible_os_family == "Debian"

    - name: create array for updates
      set_fact:
        updatelist: "{{ update_result.stdout_lines }}"
      register: updatelist_result
      when: ansible_os_family == "Debian"

    - name: create HTML report
      template:
        src: templates/patch_report_debian.j2
        dest: /var/www/html/patch_report_debian.html
      delegate_to: "{{ report_server }}"
      run_once: true
