---
- name: prepare report-server
  hosts: "{{ report_server }}"
  become: true
  vars:
    web_port: 80
  tasks:
 
  - name: install apache
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: change apache to specified port
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: 'Listen {{web_port}}'

  - name: start httpd
    ansible.builtin.service:
      name: httpd
      enabled: true
      state: started
      
  - name: allow access port 80
    ansible.posix.firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled

  - name: restart firewalld service
    ansible.builtin.service:
      name: firewalld
      enabled: true
      state: restarted

  - name: create report links
    ansible.builtin.copy:
      content: | 
        <a href=vmware_inventory_report.html> VMware Inventory Report </a><br>
        <a href=patch_report_windows.html> Patch Report Windows </a><br>
        <a href=patch_report_rhel.html> Patch Report RHEL Family </a><br>
        <a href=patch_report_debian.html> Patch Report Debian Family </a><br>
      dest: /var/www/html/index.html

  - name: display link to inventory report
    debug:
      msg:
        - "Please go to http://{{ansible_host}}:{{web_port}} to view the reports."

