---
- name: prepare report-server
  hosts: "{{ report_server }}"
  become: true
  vars:
    web_port: 80
  tasks:
 
  - name: install apache
    become: true
    yum:
      name: httpd
      state: present

  - name: change apache to specified port
    become: true
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: 'Listen {{web_port}}'

  - name: start httpd
    become: true
    service:
      name: httpd
      enabled: true
      state: started
      
  - name: allow access port 80
    ansible.posix.firewalld:
      zone: public
      port: 80
      permanent: true
      state: enabled

  - name: display link to inventory report
    debug:
      msg:
        - "Please go to http://{{ansible_host}}:{{web_port}} to view the report"

