---
- name: prepare report-server
  hosts: "{{ report_server }}"
  become: true
  vars:
    web_port: 80
  tasks:
 
  - name: install apache
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: change apache to specified port
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: 'Listen {{web_port}}'

  - name: start httpd
    ansible.builtin.service:
      name: httpd
      enabled: true
      state: started
      
  - name: allow access port 80
    ansible.posix.firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled

  - name: restart firewalld service
    ansible.builtin.service:
      name: firewalld
      enabled: true
      state: restarted

  - name: Remove file (delete file)
    ansible.builtin.copy:
      content: "This is a report server."
      dest: /var/www/html/index.html
      state: present

  - name: display link to inventory report
    debug:
      msg:
        - "Please go to http://{{ansible_host}}:{{web_port}} to view the report"

