---
- name: Gather facts from all VMs
  hosts: all
  gather_facts: false
  tasks:
    - name: print report
      debug:
        msg: "{{ hostvars[inventory_hostname]['config.name'] }} - {{ ansible_facts.os_name }} - {{ ansible_facts.uptimeSeconds }} {{ ansible_facts.os_name }} - {{ ansible_facts.memtotal_mb }}"

