---
- name: vmware inventory report
  hosts: all
  gather_facts: false
  tasks:
    - name: create vmware inventry report
      ansible.builtin.template:
        src: templates/vmware_inventory_report.j2
        dest: /var/www/html/vmware_inventory_report.html
      delegate_to: "{{ report_server }}"
      run_once: true
