---
- name: Gather facts from all VMs
  hosts: all
  gather_facts: false
  tasks:
    - name: print report
      debug:
        msg: "{{ hostvars[inventory_hostname]['config.name'] }} - {{ hostvars[inventory_hostname]['guest.guestFullName'] }} - {{ ansible_facts.uptimeSeconds | community.general.to_days }}"

