---
- name: Gather facts from all VMs
  hosts: all
  gather_facts: false
  tasks:
    - name: print report
      debug:
        msg: | 
          "{{ hostvars[inventory_hostname]['config.name'] }} -
          {{hostvars[inventory_hostname]['ansible_distribution'] }} -
          {{hostvars[inventory_hostname]['ansible_memtotal_mb'] }} -
          {{hostvars[inventory_hostname]['ansible_processor_vcpus'] }} -
          {{hostvars[inventory_hostname]['ansible_uptime_seconds'] }}  -
          {{hostvars[inventory_hostname]['powerState']}}"

