---
- name: Gather facts from all VMs
  hosts: all
  gather_facts: false
  tasks:
    - name: Create a DOS-style text file from a template
      ansible.builtin.template:
        src: templates/vmware_inventory_report.j2
        dest: /var/www/html/vmware_inventory_report.html
      delegate_to: "{{ report-server }}"
      run_once: true
