---
- name: Gather facts from all VMs
  hosts: all
  gather_facts: false
  tasks:
    - name: print report
      debug:
        msg: "{{ hostvars[inventory_hostname][item] }} - "
      loop:
      - config.name
      - guest.guestFullName
