---
- name: Gather facts from all VMs
  hosts: all
  gather_facts: false
  tasks:
    - name: print report
      debug:
        msg: | 
          "{{ hostvars[inventory_hostname]['config.name'] }} -
          {{hostvars[inventory_hostname]['guest.guestFullName'] }} -
          {{hostvars[inventory_hostname]['guest.ipAddress'] }} -
          {{hostvars[inventory_hostname]['summary.config.memorySizeMB'] }} -
          {{hostvars[inventory_hostname]['ansible_processor_vcpus'] }} -
          {{hostvars[inventory_hostname]['ansible_uptime_seconds'] }}  -
          {{hostvars[inventory_hostname]['runtime.powerState']}}"

